---
title: "Animated Global Yield Curves"
output: html_notebook
---
Set starting parameters

```{r}
library(ggplot2)
library(dplyr)
library(Rblpapi)
library(stringr)

START_DATE =  as.Date("2012-01-01","%Y-%m-%d")
END_DATE = Sys.Date()

#specify which maturities to get from the bbg yield curve vector
#this assumes the column positions the tenors are in
curveTenors<-data.frame(bbgColumns=c(3,4,5,6,7,11),tenors=factor(c(1,2,3,4,5,10)))
allSecTickers<-data_frame()
#load a csv file with the names of the BBG yield curve tickers for the countries we want
#Of the format: Ticker,Index Name,Region,CountryISO
curveTickers<-read.csv("curve tickers.csv",stringsAsFactors = FALSE)

```
Get the Bloomberg tickers for each point on the yield curve.
```{r}
# FYI the excel equivalent
#=BDH(BDS($A2,"CURVE_MEMBERS","Dir=h","startrow="&R$1&",endrow="&R$1),"PX_LAST",$M$1,$M$1,"fill=x")
blpConnect()

#first we get the individual security tickers that make up the yield curves.
for (i in  1:nrow(curveTickers)){
  secTickers<-bds(curveTickers$Ticker[i],"CURVE_MEMBERS")
  # narrow tickers down to the ones we want from curveTenors
  secTickers2<-secTickers[curveTenors$bbgColumns,]
  #print (paste(i,curveTickers$Ticker[i],curveTickers$CountryISO[i]))
  allSecTickers<-rbind(allSecTickers,data.frame(region=curveTickers$Region[i],
                                                country=curveTickers$CountryISO[i],
                                                tenor=curveTenors$tenors,
                                                secTicker=secTickers2,
                                                ticker=word(secTickers2,1)))
  
}
#don't need a factor vector for tickers
allSecTickers$secTicker=as.character(allSecTickers$secTicker)

```
Get the yield history for each security and country
```{r}
#----------------------------------

# Get BBG Data
# CAUTION: The order of the returned secs series may not be the same as order of the secs inputs
# CAUTION: There is no guarantee that the all securities will have values for the same dates.
#DEPENDS ON dplyr, stringr
tidy_bdh<-function(secs,...){
  blpConnect() #must have a valid blp session running
  blp_bdh  <-bdh(secs,...=...)
  blp_bdh_tq<-bind_rows(blp_bdh,.id='ticker') %>%
    mutate(sector=word(ticker,-1)) %>% 
    mutate(ticker=word(ticker,1)) %>% 
    select(date,ticker,everything())%>%
    group_by(sector,ticker)
  return(blp_bdh_tq)
}
# New tidy style of retrieval
#get the yields from START_DATE by BDH_OPTIONS periodicity
allYields<-tidy_bdh(allSecTickers$secTicker,
               "PX_LAST",
               start.date = START_DATE,
               options = BDH_OPTIONS)

allYields<-allSecTickers %>% left_join(allYields,by='ticker') %>% select(-secTicker,-sector)
#save the raw data
save(allYields,file="allYields.RData")
```
Massage the raw BBG data
```{r}

load("allYields.RData")
#change PX_LAST to yield
names(allYields)[6]<-"yield"
allDates<- levels(as.factor(allYields$date))
dateCount <- length(allDates)
#determine where zero will be in the overall range of all the data
yieldRange<-range(allYields$yield,na.rm=TRUE)
zeroPos<-(0-yieldRange[1])/(yieldRange[2]-yieldRange[1])

```
Build Plot
```{r}
img<-image_graph(600,400) #open magick graphics device
for (one_date in allDates){
  #interestingly, moving all the static plot elements outside the loop slows down rendering.
  one_period <- allYields %>% filter(date==one_date)
  p <- ggplot(one_period, aes(tenor, country))
  p<- p + geom_tile(aes(fill = yield), colour = "white")
  p<- p + scale_fill_gradientn(colours=c("red","white","steelblue"),
                            values=c(0,zeroPos,1),
                            na.value = "white")
  p<- p + expand_limits(fill=c(yieldRange[1]*1.1,yieldRange[2]))
  p<- p + labs(title=one_date,
               x="Years to Maturity",
               y="America           Asia                          Europe")
  p<-p + theme(axis.title.y=element_text(hjust=0))+ theme_classic()
  print(p)
}
dev.off() #close graphics device
animation <- image_animate(img, fps = 5,loop=1)
print(animation)
image_write(animation,"below_zero.gif")

```

